# Generated by Django 5.0.3 on 2024-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_image_customuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='img',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
